# Generated by Django 5.2.8 on 2026-03-25 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investimentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('descricao', models.CharField(max_length=50)),
                ('ativo', models.BooleanField(max_length=15)),
                ('detalhamento', models.TextField(blank=True, null=True)),
                ('localizacao', models.CharField(choices=[('SANTA LUCIA', 'Santa Lúcia'), ('GRANDE LESTE', 'Grande Leste'), ('SANTO EXPEDITO', 'Santo Expedito'), ('JATOBA', 'Jatobá'), ('ESCRITORIO CENTRAL', 'Escritório Central'), ('UBA', 'Uba')], max_length=20)),
                ('data', models.DateField(blank=True, null=True)),
                ('valor', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
