# Generated by Django 6.0.3 on 2026-04-07 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_alter_responsavel_cpf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investimentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('descricao', models.CharField(max_length=50)),
                ('ativo', models.BooleanField(max_length=15)),
                ('detalhamento', models.TextField(blank=True, null=True)),
                ('localizacao', models.CharField(choices=[('SANTA LUCIA', 'Santa Lúcia'), ('GRANDE LESTE', 'Grande Leste'), ('SANTO EXPEDITO', 'Santo Expedito'), ('JATOBA', 'Jatobá'), ('ESCRITORIO CENTRAL', 'Escritório Central'), ('UBA', 'Uba')], max_length=20)),
                ('data', models.DateField(blank=True, null=True)),
                ('valor', models.FloatField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investimentos', to='user.empresa')),
            ],
        ),
    ]
