# Generated by Django 6.0.3 on 2026-04-02 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tema_escuro',
            field=models.BooleanField(default=True),
        ),
    ]
