# Generated by Django 6.0.3 on 2026-04-07 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsavel',
            name='cpf',
            field=models.CharField(),
        ),
    ]
