# Generated by Django 6.0.3 on 2026-04-02 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_usuario_tema_escuro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='tema_escuro',
        ),
    ]
