# Generated by Django 6.0.3 on 2026-03-24 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ativos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d')),
                ('codigo', models.CharField(max_length=10)),
                ('descricao', models.CharField(max_length=50)),
                ('chassi', models.CharField(blank=True, max_length=50, null=True)),
                ('placa', models.CharField(blank=True, max_length=10, null=True)),
                ('adesivado', models.CharField(choices=[('ADESIVADO', 'Adesivado'), ('NAO ADESIVADO', 'Não adesivado')])),
                ('auxiliar', models.CharField(max_length=10)),
                ('cor', models.CharField(blank=True, max_length=15, null=True)),
                ('categoria', models.CharField(choices=[('MAQUINAS', 'Máquinas e implementos'), ('INFORMATICA', 'Informática e comunicação'), ('VEICULOS', 'Veículos'), ('EQUIPAMENTOS', 'Equipamentos diversos'), ('IMOVEIS', 'Imóveis'), ('MOVEIS', 'Móveis e utensílios')], max_length=20)),
                ('ativo', models.BooleanField(max_length=15)),
                ('detalhamento', models.TextField(blank=True, null=True)),
                ('localizacao', models.CharField(choices=[('SANTA LUCIA', 'Santa Lúcia'), ('GRANDE LESTE', 'Grande Leste'), ('SANTO EXPEDITO', 'Santo Expedito'), ('JATOBA', 'Jatobá'), ('ESCRITORIO CENTRAL', 'Escritório Central'), ('UBA', 'Uba')], max_length=20)),
                ('responsavel', models.CharField(blank=True, max_length=50, null=True)),
                ('incorporacao', models.DateField(blank=True, null=True)),
                ('fornecedor', models.CharField(blank=True, max_length=200, null=True)),
                ('numero_nota', models.IntegerField(blank=True, null=True)),
                ('valor', models.FloatField(blank=True, null=True)),
                ('nota', models.FileField(blank=True, upload_to='documentos/%Y/%m/%d')),
            ],
        ),
    ]
