# Generated by Django 6.0.3 on 2026-03-24 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ativos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativos',
            name='adesivado',
            field=models.BooleanField(),
        ),
    ]
