# Generated by Django 5.2.8 on 2026-03-24 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ativos', '0002_alter_ativos_adesivado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativos',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
