# Generated by Django 5.2.8 on 2026-03-26 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ativos', '0003_alter_ativos_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativos',
            name='categoria',
            field=models.CharField(choices=[('MÁQUINAS', 'Máquinas e implementos'), ('INFORMÁTICA', 'Informática e comunicação'), ('VEÍCULOS', 'Veículos'), ('EQUIPAMENTOS', 'Equipamentos diversos'), ('MÓVEIS', 'Móveis e utensílios')], max_length=20),
        ),
    ]
