# Generated by Django 5.2.8 on 2026-03-26 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ativos', '0004_alter_ativos_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativos',
            name='categoria',
            field=models.CharField(choices=[('MÁQUINAS', 'Máquinas e implementos'), ('INFORMÁTICA E COMUNICAÇÃO', 'Informática e comunicação'), ('VEÍCULOS', 'Veículos'), ('EQUIPAMENTOS DIVERSOS', 'Equipamentos diversos'), ('MÓVEIS E UTENSÍLIOS', 'Móveis e utensílios')], max_length=50),
        ),
    ]
