# Generated by Django 6.0.3 on 2026-03-27 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ativos', '0006_alter_ativos_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativos',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
