# Generated by Django 6.0.3 on 2026-04-01 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ativos', '0007_alter_ativos_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativos',
            name='categoria',
            field=models.CharField(choices=[('MÁQUINAS E IMPLEMENTOS', 'Máquinas e implementos'), ('INFORMÁTICA E COMUNICAÇÃO', 'Informática e comunicação'), ('VEÍCULOS', 'Veículos'), ('EQUIPAMENTOS DIVERSOS', 'Equipamentos diversos'), ('MÓVEIS E UTENSÍLIOS', 'Móveis e utensílios'), ('EQUIPAMENTOS OFICINA', 'Equipamentos oficina'), ('EQUIPAMENTOS UBG', 'Equipamentos UBG'), ('EQUIPAMENTOS UBA', 'Equipamentos UBA')], max_length=50),
        ),
    ]
